#!/bin/sh

# Create a repository on git.thomaslevine.com and set it up as the master for
# the current repository. Run this from the root of a git repository.
set -e

# Check that it's a git repository.
[ -d .git ] || ( echo This is not a git repository. && exit 1)

# Get the directory (repository) name
name=$(basename `pwd`)

# Remote name: origin by default
remote_name="$1"
[ "$remote_name" = '' ] && remote_name=origin

# Init
ssh git.thomaslevine.com "git init --bare $name.git"

# Register with cgit
ssh git.thomaslevine.com "
echo repo.path=/home/tlevine/$name.git >> ~/cgitrepos &&
echo repo.owner=occurrence@thomaslevine.com >> ~/cgitrepos &&
echo repo.readme=readme.md >> ~/cgitrepos"

# Add locally
git remote add "$remote_name" git.thomaslevine.com:"$name".git
git checkout master
git push -u "$remote_name" master
